### ISSUE TITLE
同学你好，一直报错找不到[\\features_model\\dt.json] 文件是为什么呀

### ISSUE THREAD

**Issue by Accel11erate** [orion-orion/TipDMCup#4]
同学你好，一直报错找不到[\\features_model\\dt.json] 文件是为什么呀

**Comment by orion-orion** [comment]
同学你好，你需要将`feature_selection`函数中的参数修改为`train`然后训练特征选择的模型哦
也就是main.py中的37行` X = feature_selection(X, y, 'predict')`这里，将`predict`修改为`train`

**Comment by orion-orion** [comment]
同学你好，目前已针对该bug更新代码，您只需要在命令行参数中设置`features_model`为`load`即可。
